In [2]:
import numpy as np
import pandas as pd

In [10]:
df = pd.read_csv('../dataset/iris.data', header=None)
df

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

prepare data for training

In [15]:
x = df.iloc[0:100, [0, 1, 2, 3]].values
x[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [22]:
y = df.iloc[0:100, 4].values

random_draws = np.random.choice(np.arange(100), 5)
y[random_draws]

array(['Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [23]:
y = np.where(y == 'Iris-setosa', 0, 1)
y[random_draws]

array([1, 0, 1, 1, 1])

split data into training and testing sets

In [24]:
x_train = np.empty((80, 4))
x_test = np.empty((20, 4))
y_train = np.empty(80)
y_test = np.empty(20)

In [27]:
# for each breed, split data into two parts 
x_train[:40], x_train[40:] = x[:40], x[50:90]
x_test[:10], x_test[10:] = x[40:50], x[90:100]
y_train[:40], y_train[40:] = y[:40], y[50:90]
y_test[:10], y_test[10:] = y[40:50], y[90:100]

activation function and learning process

In [28]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [29]:
def activation(x, w, b):
    return sigmoid(np.dot(x, w) + b)

In [33]:
def update(x, y, w, b, eta):
    y_pred = activation(x, w, b)
    a = (y_pred - y_train) * y_pred * (1 - y_pred)
    for i in range(4):
        w[i] -= eta * 1 / float(len(y)) * np.sum(a * x[:, i])

    b -= eta * 1 / float(len(y)) * np.sum(a * 1)
    return w, b

training

In [38]:
weights = np.ones(4) / 10
bias = np.ones(1) / 10
epoch = 999
for _ in range(epoch):
    weights, bias = update(x_train, y_train, weights, bias, eta=0.1)

print(f"weights={weights}, bias={bias}")

weights=[-0.32321875 -1.0269402   1.59194442  0.77334988], bias=[-0.11241777]


evaluation

In [34]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [39]:
activation(x_test, weights, bias)

array([0.04647418, 0.16419619, 0.06935813, 0.09016014, 0.08873561,
       0.09246002, 0.0491993 , 0.07571526, 0.04383201, 0.06099539,
       0.96683106, 0.96233971, 0.93330901, 0.87394427, 0.95240851,
       0.92947162, 0.9403989 , 0.9402634 , 0.7855545 , 0.9371522 ])